Repository SDSC-ORD/gimie, pull requests merged in 2023-10, with the labels that each got.

#79 feat(github.py): Get "forked from" property of a repository
  gimie/sources/github.py
  gimie/sources/gitlab.py
Labels: enhancement

#87 feat: conventional PRs
  .github/workflows/conventional-prs.yml
Labels: enhancement

#91 fix(docker): push action was missing buildx
  .github/workflows/docker-publish.yml
Labels: bug

#93 refactor(io): simplify resource interface
  gimie/io.py
Labels: refactor

#96 refactor: simplify extractor
  .github/workflows/conventional-prs.yml
  .github/workflows/sphinx-docs.yml
  README.md
  gimie/cli.py
  gimie/models.py
  gimie/project.py
  gimie/sources/abstract.py
  gimie/sources/git.py
  gimie/sources/github.py
  gimie/sources/gitlab.py
  tests/test_git.py
  tests/test_github.py
  tests/test_gitlab.py
  tests/test_output.py
Labels: refactor
